### ISSUE TITLE
DeviceSegmentedRadixSort::SortPairsDescending does not work because of inlined PtxVersion

### ISSUE THREAD

**Issue by koenvandesande** [NVIDIA/cub#260] opened 2021-02-01 16:00 UTC
If you use the `cub::DeviceSegmentedRadixSort::SortPairsDescending` function with the DoubleBuffer interface, everything is fine. However, the other interface (this one https://nvlabs.github.io/cub/structcub_1_1_device_segmented_radix_sort.html#a86f4958fde5074bf8196e87078a3cf70 )
based on d_keys_in and d_keys_out will internally create a DoubleBufer with (in, out), casting away constness on the input. And then does not use the "Current" on the DoubleBuffer to get the output, which in practice means the output is actually written into the input buffer. See the following code where the DoubleBuffer creation happens:
https://github.com/NVIDIA/cub/blob/8128ac8489e0f2d3dd82425bac24020367f72fe8/cub/device/device_radix_sort.cuh#L165
I'm not sure how to fix this within the API. My current thinking is to start using the DoubeBuffer API. Should the other API be deprecated?

Or is my understanding of the API incomplete, and is this 'fixed' by `is_overwrite_okay` ?

**Comment by koenvandesande** [comment] 2021-02-01 16:53
I've found that I have an error elsewhere, which I'm looking into now:
```
CUDA error 101 [/usr/local/cuda/include/cub/block/../iterator/../util_device.cuh, 472]: invalid device ordinal
CUDA error 101 [/usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh, 1911]: invalid device ordinal
```
It's strange because I'm launching the functions with a (valid) stream argument.

**Comment by allisonvacanti** [comment] 2021-02-01 20:12
Thanks for the report. It sounds like the `is_overwrite_okay` flag should prevent this behavior, and it looks like it's correctly set to `false` for the pointer overload of `cub::DeviceSegmentedRadixSort::SortPairsDescending`.

It'll take some debugging to figure out why that flag isn't working, but in the meantime you can workaround this by copying the input data into a 3rd set of key/value buffers prior to calling the sort. This is what (should be) happening internally in `cub::DispatchSegmentedRadixSort` when `is_overwrite_okay=false`, though it seems broken.

It may be a while before I have time to debug this. If you can provide a small, simple CUB-only reproducer that would help speed things up :)

For the other issue:

> invalid device ordinal

This sounds similar to a recent regression reported in issue NVIDIA/thrust#1371, which is fixed by PR NVIDIA/cub#259. The fix was a 2-line patch to one of the CUB headers -- try it out locally and see if that fixes the problem for you.

**Comment by koenvandesande** [comment] 2021-02-02 09:17
The reason for my first problem is actually the invalid device ordinal; no CUDA kernels are executing so no valid output is generated. There's nothing wrong with the sort function.
The fix by PR #259 is insufficient to fix it. It does not fix the PtxVersion function. If I replace **all** occurences of `__force_inline__` from the `device_util.cuh` file, then it works again.
I've tried removing `__force_inline__` from just `PtxVersion`, `PtxVersionUncached`, `CurrentDevice` and `SwitchDevice`, but that was not enough.

**Comment by allisonvacanti** [comment] 2021-02-02 19:25
That's troubling.

What is the output of `nvcc --version`, and what host compiler (including version) are you using? I'm going to take a closer look at this and submit a bug report to the compiler team. If you have a small reproducer for the issue that would also be helpful.

**Comment by allisonvacanti** [comment] 2022-05-09 20:30
Expired.

**Closed by allisonvacanti** 2022-05-09 20:30 UTC
Labels: type: bug: functional
