### ISSUE TITLE
how to use dynamic shared memory in cub block radix sort

### ISSUE THREAD

**Issue by zlwu92** [NVIDIA/cub#644] opened 2023-03-08 08:02 UTC
Hi,

I'm a new user to cub library and have a question when i use cub block radix sort to sort an array, the provided example are for static shared mem, and I encounter problems when the array is very large, and get compiler error says that the shared size I need is larger than maximal which is 48kb I think. So I think I need to use dynamic shared memory in it. So could you give me an example how to incorperate dynamic memory scheme in radix sort kernel? Thanks! Actually I found example for block_reduce, but it seems do not fit for radix sort, is it because currently radix sort do not support dynamic shared memory version?

What should I do if I want to use block sort to sort an array larger than 100000? 
How should I set the ITEMS_PER_THREAD value if I need to use dynamic shared memory for block radix sort? Because it seems that I still need to pass this as template params to kernel which will obtained during compile time. I have to set it as a constant value?
```[tasklist]

```

**Comment by senior-zero** [comment] 2023-03-08 15:56
Hello @zlwu92! This issue is a duplicate of the following [one](https://github.com/NVIDIA/cub/issues/327#issuecomment-1250816657) and probably the [one](https://github.com/NVIDIA/cub/issues/292) you've already discovered. Mentioned issues illustrate a way to sort dynamic problem sizes with CUB facilities. So I'll close this issue. 

Regarding your question on the dynamic shared memory allocation, even A100 doesn't contain enough shared memory for block radix sort to handle 100000 elements at once. To sort problem sizes of this magnitude, you'd have to resort to the code I've mentioned. If you have smaller problem sizes, or would like to increase block radix sort tile size, you can take a look at the [example](https://github.com/NVIDIA/cub/blob/main/examples/block/example_block_reduce_dyn_smem.cu) of dynamic shared memory usage in CUB.

**Closed by senior-zero** 2023-03-08 15:56 UTC

**Comment by zlwu92** [comment] 2023-03-09 08:13
Hi,

I found an implementation that uses global memory. [link](https://stackoverflow.com/questions/22138497/cub-blockradixsort-how-to-deal-with-large-tile-size-or-sort-multiple-tiles)


```
#define HEDGEN 102400
#define THREAD_PER_BLOCK 512
#define NUM_PER_THREAD 200

typedef BlockRadixSort<unsigned, THREAD_PER_BLOCK, NUM_PER_THREAD> my_block_sort;
__device__ typename my_block_sort::TempStorage sort_temp_stg;

template <int BLOCK_THREADS, int ITEMS_PER_THREAD>
__global__ void BlockSortKernel(unsigned* d_in) {
    my_block_sort(sort_temp_stg).Sort(*static_cast<unsigned(*)[ITEMS_PER_THREAD]>(static_cast<void*>(d_in + (threadIdx.x * ITEMS_PER_THREAD))));
}

int main(int argc, char** argv) {
      ....
      unsigned* d_par_list;
      CHECK_ERROR(cudaMalloc((void**)&d_par_list, HEDGEN * sizeof(unsigned)));
      BlockSortKernel<THREAD_PER_BLOCK, NUM_PER_THREAD><<<1, THREAD_PER_BLOCK>>>(d_par_list);
      ....
}
```
Above is my implementation, but I got a problem when I test for HEDGEN = 102400 (input_size), then I cannot get correct result. Many of the output are zeros. But I use the global memory when calling the BlockRadixSort::Sort(). Is because of this api have some problems with this kind of cases? I checked that the result before sort is correct, after sorting is wrong. I also test array_length = 81920 is correct, when increase to 102400, it's wrong. I have no idea about the reason.

**Comment by senior-zero** [comment] 2023-03-10 13:36
@zlwu92 your code doesn't sort the data because the kernel is probably never launched. This number of items will definitely take more than 240 registers per thread. You are trying to launch 512 threads with 240+ registers. The register file is not large enough to hold that, so kernel launch fails due to insufficient resources. 

You can reduce the block size, but you won't be able to sort more than `65535` items because that's the limit of some internal counters. I'll create a PR that would static assert the tile size to prevent issue like that at compile time. 

Please, take a look at the following [solution](https://github.com/NVIDIA/cub/issues/327#issuecomment-1250816657) instead.

**Comment by zlwu92** [comment] 2023-03-12 12:13
I see. Thanks. So if I use block scan on an array of this much length. Will I also encounter this problem as using block sort?

**Comment by senior-zero** [comment] 2023-03-12 16:28
@zlwu92 I don't anticipate this to be an issue with scan because you have control over what type is used for accumulation results. Let us know if you discover issues there.

**Comment by zlwu92** [comment] 2023-03-17 15:03
Another questions If I have many (more than millions of long arrays to be sorted), which one should I choose to use in order to make this process as fast as possible. Because I think when I use device radix sort in a for loop, it may launch many kernels and this overhead might be quite large, even slower than using host cpu std::sort(), is that correct?

**Comment by zlwu92** [comment] 2023-03-17 15:16
And for the device sort, I take look at the example in this repo, it seems I have to construct a key array? If I just want to sort an array of values without any keys, can you give an example that how should I apply that? Thanks.

**Comment by zlwu92** [comment] 2023-03-17 15:24
> > Another questions If I have many (more than millions of long arrays to be sorted), which one should I choose to use in order to make this process as fast as possible. Because I think when I use device radix sort in a for loop, it may launch many kernels and this overhead might be quite large, even slower than using host cpu std::sort(), is that correct?
> 
> @zlwu92 can you consider using [cub::DeviceSegmentedSort](https://github.com/NVIDIA/cub/blob/a9c11ec8ac2612d28e21799245300ebdef6832d2/cub/device/device_segmented_sort.cuh#L115)?
> 
> In my case, different segments has different length, can I just use this api, calling once can achieve my goal?

**Comment by senior-zero** [comment] 2023-03-17 15:38
@zlwu92 each segment can be of different size. Please, take a look at the [documentation](https://github.com/NVIDIA/cub/blob/a9c11ec8ac2612d28e21799245300ebdef6832d2/cub/device/device_segmented_sort.cuh#L80-L112).

**Comment by zlwu92** [comment] 2023-03-18 02:23
Hi, I have tried the deviceSegmentedSort. Below is my test code.
```
#include <iostream>
#include <algorithm>
#include <thrust/find.h>
#include <thrust/host_vector.h>
#include <thrust/device_vector.h>
#include <thrust/unique.h>
#include <thrust/execution_policy.h>
#include <thrust/sort.h>
#include <cub/cub.cuh>
#include <cub/block/block_load.cuh>
#include <cub/block/block_store.cuh>
#include <cub/block/block_radix_sort.cuh>
#include <cub/device/device_segmented_sort.cuh>

#include <bits/stdc++.h>
#include <chrono>

// error macro
#define CHECK_ERROR(err)    checkCudaError(err, __FILE__, __LINE__)
#define GET_LAST_ERR()      getCudaLastErr(__FILE__, __LINE__)

inline void getCudaLastErr(const char *file, const int line) {
    cudaError_t err;
    if ((err = cudaGetLastError()) != cudaSuccess) {
        std::cerr << "CUDA error: " << file << "(" << line << "): " << cudaGetErrorString(err) << "\n";
        exit(EXIT_FAILURE);
    }
}

inline void checkCudaError(cudaError_t err, const char *file, const int line) {
    if (err != cudaSuccess) {
        std::cerr << "CUDA error: " << file << "(" << line << "): " << cudaGetErrorString(err) << "\n";
        exit(EXIT_FAILURE);
    }
}
  
// convenient timers
#define TIMERSTART(label)                                                    \
        cudaSetDevice(0);                                                    \
        cudaEvent_t start##label, stop##label;                               \
        float time##label;                                                   \
        cudaEventCreate(&start##label);                                      \
        cudaEventCreate(&stop##label);                                       \
        cudaEventRecord(start##label, 0);

#define TIMERSTOP(label)                                                     \
        cudaSetDevice(0);                                                    \
        cudaEventRecord(stop##label, 0);                                     \
        cudaEventSynchronize(stop##label);                                   \
        cudaEventElapsedTime(&time##label, start##label, stop##label);       \
        std::cout << "kernel execution time: #" << time##label                                      \
                  << " ms (" << #label << ")" << std::endl;


using namespace cub;

int main(int argc, char** argv) {
    unsigned num_segments = 13995; // num_segments
    char *filepath = argv[1];
    std::ifstream f(filepath);
    std::string line;
    std::vector<unsigned int> edges_id;
    int count = 0;
    int totalsize = 0;
    unsigned* h_deg = (unsigned*)malloc(num_segments * sizeof(unsigned));
    memset(h_deg, 0, num_segments * sizeof(unsigned));
    while (std::getline(f, line)) {
        int val;
        std::stringstream ss(line);
        while (ss >> val) {
            edges_id.push_back(val);
            totalsize++;
            h_deg[count]++;
        }
        count++;
    }
    unsigned* h_off = (unsigned*)malloc((num_segments + 1) * sizeof(unsigned));
    memset(h_off, 0, (num_segments + 1) * sizeof(unsigned));
    for (int i = 1; i < (num_segments + 1); ++i) {
        h_off[i] = h_deg[i-1] + h_off[i-1];
    }
    std::cout << "totalpinsize: " << totalsize << "\n"; // num_items
    // for (int i = 0; i < num_segments + 1; ++i) {
    //     std::cout << h_off[i] << " ";
    // }
    unsigned* d_off;
    CHECK_ERROR(cudaMalloc((void**)&d_off, (num_segments + 1) * sizeof(unsigned)));
    CHECK_ERROR(cudaMemcpy(d_off, h_off, (num_segments + 1) * sizeof(unsigned), cudaMemcpyHostToDevice));

    unsigned* pin_list; // d_keys_in
    CHECK_ERROR(cudaMalloc((void**)&pin_list, totalsize * sizeof(unsigned)));
    CHECK_ERROR(cudaMemcpy(pin_list, &edges_id[0], totalsize * sizeof(unsigned), cudaMemcpyHostToDevice));
    // std::ofstream in("segmented_sort_input.txt");
    // for (int i = 0; i < num_segments; ++i) {
    //     for (int j = 0; j < h_deg[i]; ++j) {
    //         in << edges_id[h_off[i] + j] << " ";
    //     }
    //     in << "\n";
    // }
    unsigned* out_pins;
    CHECK_ERROR(cudaMalloc((void**)&out_pins, totalsize * sizeof(unsigned)));
    void* d_temp_storage = NULL;
    size_t temp_storage_bytes = 0;
    TIMERSTART(0)
    cub::DeviceSegmentedSort::SortKeys(d_temp_storage, temp_storage_bytes, pin_list, out_pins, totalsize, num_segments, d_off, d_off+1);
    TIMERSTOP(0)
    
    std::cout << "temp_storage_bytes: " << temp_storage_bytes << " bytes.\n";
    std::cout << "temp_storage_in_GB: " << temp_storage_bytes / (1024.f * 1024.f * 1024.f) << " GB.\n";
    TIMERSTART(1)
    cub::DeviceSegmentedSort::SortKeys(d_temp_storage, temp_storage_bytes, pin_list, out_pins, totalsize, num_segments, d_off, d_off+1);
    TIMERSTOP(1)

    unsigned* h_outpins = (unsigned*)malloc(totalsize * sizeof(unsigned));
    CHECK_ERROR(cudaMemcpy(h_outpins, out_pins, totalsize * sizeof(unsigned), cudaMemcpyDeviceToHost));
    std::ofstream debug("segmented_sort_result.txt");
    for (int i = 0; i < num_segments; ++i) {
        for (int j = 0; j < h_deg[i]; ++j) {
            debug << h_outpins[h_off[i] + j] << " ";
        }
        debug << "\n";
    }
    
    GET_LAST_ERR();
    CHECK_ERROR(cudaFree(d_temp_storage));
    CHECK_ERROR(cudaFree(out_pins));
    CHECK_ERROR(cudaFree(pin_list));
    CHECK_ERROR(cudaFree(d_off));
    return 0;
}

```

**Comment by zlwu92** [comment] 2023-03-26 02:41
Hi, 

I also want to know if there's any support for segmented scan functionality? If not how can we use any alternatives to achieve this? Thanks.

**Comment by senior-zero** [comment] 2023-03-26 08:15
Hello @zlwu92!

I've noticed that you've been adding more questions to the closed GitHub issue. While we appreciate your engagement and interest in the project, it would be more helpful and organized if you could create separate GitHub discussions for each of your new questions in the future.

As a one-time exception, I will answer your question here. However, for any subsequent questions, please create separate GitHub discussions. This will allow other contributors to easily find and engage in the discussions related to their areas of interest or expertise. Additionally, it will help maintain the clarity and focus of the original issue, ensuring that any future users can easily reference it without being overwhelmed by unrelated information.

Regarding the segmented scan, CUB doesn't provide API for that. However, the same functionality can be achieved with scan by key:

```cpp
#include <cub/cub.cuh>

#include <thrust/binary_search.h>
#include <thrust/device_vector.h>
#include <thrust/iterator/counting_iterator.h>
#include <thrust/iterator/transform_iterator.h>
#include <thrust/sequence.h>

#include <cuda/std/functional>

#include <iostream>

struct map_t
{
  const int *d_map;
  __host__ __device__ int operator()(int i) const { return d_map[i]; }
};

struct search_t
{
  const int *d_offsets;
  int num_segments;

  __device__ int operator()(int i) const
  {
    return thrust::distance(
             d_offsets,
             thrust::upper_bound(thrust::seq, d_offsets, d_offsets + num_segments, i)) -
           1;
  }
};

template <class Fn>
void segmented_scan(const int n, Fn fn)
{
  thrust::device_vector<int> values(n, 1);

  auto keys = thrust::make_transform_iterator(thrust::make_counting_iterator(0), fn);

  std::uint8_t *d_temp_storage   = nullptr;
  std::size_t temp_storage_bytes = 0;

  cub::DeviceScan::ExclusiveScanByKey(d_temp_storage,
                                      temp_storage_bytes,
                                      keys,
                                      values.begin(),
                                      values.begin(),
                                      cuda::std::plus<int>{},
                                      0,
                                      n);

  thrust::device_vector<std::uint8_t> temp_storage(temp_storage_bytes);
  d_temp_storage = thrust::raw_pointer_cast(temp_storage.data());

  cudaEvent_t begin, end;
  cudaEventCreate(&begin);
  cudaEventCreate(&end);

  cudaEventRecord(begin);
  cub::DeviceScan::ExclusiveScanByKey(d_temp_storage,
                                      temp_storage_bytes,
                                      keys,
                                      values.begin(),
                                      values.begin(),
                                      cuda::std::plus<int>{},
                                      0,
                                      n);
  cudaEventRecord(end);
  cudaEventSynchronize(end);

  float ms;
  cudaEventElapsedTime(&ms, begin, end);
  std::cout << ms << "ms" << std::endl;
}

void segmented_scan(int num_items,
                    int num_segments,
                    const thrust::device_vector<int> &map,
                    const thrust::device_vector<int> &offsets)
{
  std::cout << "map: ";
  segmented_scan(num_items, map_t{thrust::raw_pointer_cast(map.data())});

  std::cout << "search: ";
  segmented_scan(num_items, search_t{thrust::raw_pointer_cast(map.data()), num_segments});
}

int main()
{
  {
    const int num_items    = 1 << 19;
    const int num_segments = num_items;
    thrust::device_vector<int> map(num_items + 1);
    thrust::sequence(map.begin(), map.end());

    segmented_scan(num_items, num_segments, map, map);
  }

  {
    const int num_items    = 1 << 19;
    const int num_segments = 2;
    thrust::device_vector<int> map(num_items);
    thrust::sequence(map.begin(), map.end());

    thrust::device_vector<int> offsets(num_segments + 1);
    offsets[0] = 0;
    offsets[1] = num_items / 2;
    offsets[2] = num_items;

    segmented_scan(num_items, num_segments, map, map);
  }
}

/*
map: 0.02048ms
search: 0.07168ms
map: 0.02048ms
search: 0.017408ms
*/
```

Note that the code above illustrates two approaches. If you'd like to optimize for space or a small number of segments, you could rely on binary search. If you optimize for runtime, it'd be more efficient to assign each element a corresponding key representing segment id. 

Regarding the warp scan, you are correct. At the moment, we allow only one item per thread to be passed in warp scan.
