### ISSUE TITLE
Issue when call cub::DeviceScan::InclusiveSum in a stream

### ISSUE THREAD

**Issue by zenRJG** [NVIDIA/cub#134] opened 2018-04-24 16:00 UTC
I called cub::DeviceScan::InclusiveSum in a Cuda stream but the result is not stable. This stream launches firstly a Cuda kernel (A), then calls cub::DeviceScan::InclusiveSum to compute the output of A and finally calls another Cuda Kernel (B) that uses the output of cub sum. The result is always correct when stream is 0 or without stream setup, but result is sometime wrong or with a real stream.  When I replace cub::DeviceScan::InclusiveSum by thrust::InclusiveSum, the result is always correct. Does someone has idea about this issue?

**Comment by RaulPPelaez** [comment] 2018-04-25 09:12
Sounds like a synchronization problem, but without code to see who knows...
Stream 0 is special, kernels in stream 0 will stall the CPU until the kernel ends.
https://stackoverflow.com/questions/13331995/concurrency-of-cuda-default-stream-with-created-streams   Try using a stream but call cudaStreamSynchronize(st) after each kernel, you will see the result is correct as well most probably. 
Are you running the thrust version in the stream as well? thrust is probably synchronizing before giving you control back.

**Comment by zzhangfr** [comment] 2019-04-04 12:55
The problem is found, cub::DeviceScan::InclusiveSum call two kernels, the one initialize and decide the block configuration basing on the PTX_ARCH, and the second kernel compute the result. I traced the kernels calling found this block configuration will be changed once a cuda errer occurs just between these two kernels.

**Comment by allisonvacanti** [comment] 2020-10-20 21:40
Do you have a minimal example that reproduces the error you're seeing?

**Comment by allisonvacanti** [comment] 2022-05-06 22:22
Closing as expired -- please provide an example that replicates this behavior if it is still an issue.

**Closed by allisonvacanti** 2022-05-06 22:22 UTC
Labels: info needed
