### ISSUE TITLE
Question: __threadfence() inside loop to prevent hoisting

### ISSUE THREAD

**Issue by nayakajay** [NVIDIA/cub#345] opened 2021-07-13 18:51 UTC
I am trying to understand the code and trying to relate them with the comments. 
I came across [WaitForValid](https://github.com/NVIDIA/cub/blob/main/cub/agent/single_pass_scan_operators.cuh#L425) __device__ function in ```agent/single_pass_scan_operators.cuh```. 

I wanted to know why the fence is inside the ```do ... while();``` loop. 
The comment suggests that this is to prevent hoisting loads from below. The fence outside the loop will do that too. 
There are no other loads in the loop, and the address being loaded in the loop is the same. 

Is there a scenario I am missing? Is there some optimization that the compiler does which needs to be prevented? 
Any such pointers will be great!

**Comment by senior-zero** [comment] 2021-07-14 22:35
Hello, @nayakajay! 

Thank you for the interesting question. As I understand, hoisting is about [moving invariants out of the loops](https://compileroptimizations.com/category/hoisting.htm). Because `d_tile_status` isn't marked as volatile, in theory, the load can be hoisted. The volatile keyword in the inline PTX of `ThreadLoad` [doesn't prevent](https://docs.nvidia.com/cuda/inline-ptx-assembly/index.html#incorrect-optimization) memory optimizations, the memory clobbers do. The memory clobbers aren't used in `ThreadLoad`. Although I [couldn't force](https://cuda.godbolt.org/z/h8vEn93a8) the compiler to hoist loads in this case, I'm not sure that it can't. 

From the memory model point of view, we only need a fence after the loop in this case. But this modification will require marking the `d_tile_status` as volatile. I'm not sure why it was not. For me, it seems like a possible optimization.

**Comment by senior-zero** [comment] 2021-07-15 16:37
I haven't considered that the volatile load and CG load produces different instructions. Volatile load produce `LDG.E.STRONG.SYS` while `cub::ThreadLoad<cub::LOAD_CG>` load produces `LD.E.CG`. 
I've written [the code ](https://gist.github.com/senior-zero/1139726ea4850a65f15c9c228fc2a17d) that reproduces memory access patterns in the decoupled look back. It seems that the volatile and relaxed loads perform at the same speed and are 19% faster than the CG load + fence on RTX 3090.  I suppose we should go ahead and use new relaxed qualifiers instead of threadfence + CG. 

```cuda
__device__ int load_relaxed(int * flag)
{
    int reg;
    asm volatile ("ld.relaxed.gpu.b32 %0, [%1];" : "=r"(reg) : "l"(flag) : "memory");
    return reg;
}
```

Please, feel free to reopen this issue if you have other questions in this regard.

**Closed by senior-zero** 2021-07-15 16:37 UTC
Labels: question

**Comment by nayakajay** [comment] 2021-07-16 06:20
Thanks for the reply, I was wondering about code-hoisting. I can understand about compiler hoisting out loop invariants in the example showed in the link, but for a **multi-threaded** code, I thought it may not be the case. Maybe, I should look up into it a bit more. 
I tried the code you shared and prepared a variant just to look at the generated SASS [here](https://gist.github.com/nayakajay/86d83ff3ffc8230e7c160d2e25caf63e). I compiled the code simply with ```nvcc volatile_relaxed_cg.cu -arch=sm_70``` (I tried it with 75 and 86 too). The SASS output gives me the load being ```STRONG``` for all arch. I am assuming your compilition tool-chain is not deviating too much from this, correct me there. The SASS seems a bit different from what you mentioned.

SASS output (just attaching the cg kernel)
```
		Function : _Z9kernel_cgPi
	.headerflags    @"EF_CUDA_SM70 EF_CUDA_PTX_SM(EF_CUDA_SM70)"
        /0000/                   MOV R1, c[0x0][0x28] ;              /* 0x00000a0000017a02 */
                                                                       /* 0x000fd00000000f00 */
        /0010/              @!PT SHFL.IDX PT, RZ, RZ, RZ, RZ ;       /* 0x000000fffffff389 */
                                                                       /* 0x000fe200000e00ff */
        /0020/                   MOV R2, c[0x0][0x160] ;             /* 0x0000580000027a02 */
                                                                       /* 0x000fe40000000f00 */
        /0030/                   MOV R3, c[0x0][0x164] ;             /* 0x0000590000037a02 */
                                                                       /* 0x000fd00000000f00 */
        /0040/                   LD.E.STRONG.GPU R5, [R2] ;          /* 0x0000000002057980 */
                                                                       /* 0x000ea80000114900 */
        /0050/                   STG.E.SYS [R2], R5 ;                /* 0x0000000502007386 */
                                                                       /* 0x004fe2000010e900 */
        /0060/                   EXIT ;                              /* 0x000000000000794d */
                                                                       /* 0x000fea0003800000 */
        /0070/                   BRA 0x70;                           /* 0xfffffff000007947 */
                                                                       /* 0x000fc0000383ffff */
```

**Comment by senior-zero** [comment] 2021-07-16 09:07
That's right @nayakajay. The generated SASS instruction is marked as `STRONG` in all cases. The point was about it being marked as `.SYS` or `.GPU`. Here is an example of [this difference](https://cuda.godbolt.org/z/ec4cTcqra). 

Regarding hoisting in multi-threaded code - you can check [this talk](https://youtu.be/VJ1QLrmfQws). There's an example of load hoisting on slide 35. It's a bit different because the load is non-coherent. But the thing is - you can only rely on the [PTX memory model](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#memory-consistency-model). The only strong operations there are: `.relaxed, .acquire, .release, .acq_rel or .volatile`. As you [can see here](https://cuda.godbolt.org/z/WvoxceEdn) `cub::ThreadLoad<cub::LOAD_CG>` generates `ld.cg.u32` so there is no guarantees from the compiler point of view. Therefore, the only possible solution is to have a fence inside the loop and CG load or use .relaxed or .volatile qualifier along with the fence after the spin loop. The gist above is meant to demonstrate that the .relaxed load is faster than CG and fence.
