### ISSUE TITLE
Is it possible to radix sort a struct?

### ISSUE THREAD

**Issue by alibillalhammoud** [NVIDIA/cub#643] opened 2023-03-05 01:09 UTC
Say I have a struct (assume it is packed):  
```
struct u40bits{
    uint8_t LSbits;
    uint32_t MSbits;
};
```   
Correct me if I am wrong but I do not think I can apply cub radix sort to an array of u40bits.  

Say I have this struct:   
```
struct u64bits{
    uint32_t LSbits;
    uint32_t MSbits;
};
```   
I can apply radix sort to an array of u64bits by changing the ptr to my array u64bits* -> uint64_t*

Is there a reason in the implementation why the first is not allowed? i.e. Would it not be possible to apply the exact same radix sort algorithm to u40bits?

**Comment by senior-zero** [comment] 2023-03-05 06:25
Hello @alibillalhammoud! This issue is a duplicate of the following [one](https://github.com/NVIDIA/cub/issues/52), so I'm closing it as a duplicate. 

Regarding your question, it's too easy to have issues on the user side by allowing this kind of behaviour. There might be padding bits in the user type, or it might contain a floating point member variable. In both cases, we'll provide wrong results but a successful compilation. I'm currently working on a more generic solution where you can let us know about primitive members that you treat as keys. I expect this functionality to be merged in about a month.

**Closed by senior-zero** 2023-03-05 06:25 UTC
